# Generated by Django 5.2.5 on 2025-08-10 20:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Cihaz Adı')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Konum')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Son Görülme')),
                ('health_status', models.JSONField(blank=True, default=dict, null=True, verbose_name='Sağlık Durumu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cihaz Sahibi')),
            ],
            options={
                'verbose_name': 'Cihaz',
                'verbose_name_plural': 'Cihazlar',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Sensör Adı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('interface', models.CharField(choices=[('serial', 'Seri Port'), ('i2c', 'I2C'), ('virtual', 'Sanal')], max_length=20, verbose_name='Arayüz Tipi')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Arayüz Yapılandırması (JSON)')),
                ('parser_type', models.CharField(choices=[('regex', 'Regex'), ('binary', 'Binary'), ('simple', 'Basit')], max_length=20, verbose_name='Veri Ayrıştırıcı Tipi')),
                ('parser_config', models.JSONField(blank=True, default=dict, verbose_name='Ayrıştırıcı Yapılandırması (JSON)')),
                ('read_interval', models.PositiveIntegerField(default=60, verbose_name='Okuma Sıklığı (Saniye)')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='core.device', verbose_name='Bağlı Olduğu Cihaz')),
            ],
            options={
                'verbose_name': 'Sensör',
                'verbose_name_plural': 'Sensörler',
                'unique_together': {('device', 'name')},
            },
        ),
    ]
