# Generated by Django 5.2.5 on 2025-08-10 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(verbose_name='Ölçüm Değeri')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Zaman Damgası')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='core.sensor', verbose_name='Sensör')),
            ],
            options={
                'verbose_name': 'Sensör Okuması',
                'verbose_name_plural': 'Sensör Okumaları',
                'ordering': ['-timestamp'],
            },
        ),
    ]
