# Generated by Django 5.2.5 on 2025-08-10 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sensorreading'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Kural Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trigger_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sensor', verbose_name='Tetikleyici Sensör')),
            ],
            options={
                'verbose_name': 'Kural',
                'verbose_name_plural': 'Kurallar',
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_key', models.CharField(max_length=100, verbose_name='Değişken Anahtarı (JSON Key)')),
                ('operator', models.CharField(choices=[('>', 'Büyüktür'), ('>=', 'Büyük veya Eşittir'), ('<', 'Küçüktür'), ('<=', 'Küçük veya Eşittir'), ('==', 'Eşittir'), ('!=', 'Eşit Değildir')], max_length=4, verbose_name='Operatör')),
                ('comparison_value', models.CharField(max_length=100, verbose_name='Karşılaştırma Değeri')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='core.rule', verbose_name='Ait Olduğu Kural')),
            ],
            options={
                'verbose_name': 'Koşul',
                'verbose_name_plural': 'Koşullar',
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('log_to_console', 'Sunucu Konsoluna Yaz')], max_length=20, verbose_name='Eylem Tipi')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Eylem Yapılandırması (JSON)')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.rule', verbose_name='Ait Olduğu Kural')),
            ],
            options={
                'verbose_name': 'Eylem',
                'verbose_name_plural': 'Eylemler',
            },
        ),
    ]
