# Generated by Django 5.2.5 on 2025-08-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rule_condition_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Alıcı Adı (örn: Proje Sorumlusu)')),
                ('recipient_type', models.CharField(choices=[('email', 'E-posta')], max_length=10, verbose_name='Alıcı Tipi')),
                ('address', models.CharField(max_length=255, verbose_name='Adres (e-posta, telefon no, vb.)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
            ],
            options={
                'verbose_name': 'Bildirim Alıcısı',
                'verbose_name_plural': 'Bildirim Alıcıları',
            },
        ),
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('log_to_console', 'Sunucu Konsoluna Yaz'), ('send_email', 'E-posta Gönder')], max_length=20, verbose_name='Eylem Tipi'),
        ),
        migrations.AddField(
            model_name='action',
            name='recipients',
            field=models.ManyToManyField(blank=True, to='core.notificationrecipient', verbose_name='Bildirim Alıcıları'),
        ),
    ]
