# Generated by Django 5.2.5 on 2025-08-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notificationrecipient_alter_action_action_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Enlem'),
        ),
        migrations.AddField(
            model_name='device',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Boylam'),
        ),
    ]
