# Generated by Django 5.2.5 on 2025-08-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_device_latitude_device_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='cooldown_minutes',
            field=models.PositiveIntegerField(default=60, verbose_name='Tekrar Bildirme Sıklığı (Dakika)'),
        ),
        migrations.AddField(
            model_name='rule',
            name='last_triggered',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son Tetiklenme Zamanı'),
        ),
    ]
