# Generated by Django 5.2.5 on 2025-08-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rule_cooldown_minutes_rule_last_triggered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='parser_type',
            field=models.CharField(choices=[('regex', 'Regex'), ('binary', 'Binary Format'), ('simple', 'Basit (Değerin kendisi)')], max_length=20, verbose_name='Veri Ayrıştırıcı Tipi'),
        ),
    ]
