# Generated by Django 5.2.5 on 2025-08-11 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_sensor_parser_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('message', models.TextField(verbose_name='Uyarı Mesajı')),
                ('is_acknowledged', models.BooleanField(default=False, verbose_name='Görüldü mü?')),
                ('severity', models.CharField(choices=[('info', 'Bilgi'), ('warning', 'Uyarı'), ('critical', 'Kritik')], default='warning', max_length=10, verbose_name='Önem Derecesi')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.device')),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.rule', verbose_name='Tetikleyen Kural')),
            ],
            options={
                'verbose_name': 'Uyarı',
                'verbose_name_plural': 'Uyarılar',
                'ordering': ['-timestamp'],
            },
        ),
    ]
