# Generated by Django 5.2.5 on 2025-08-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='interface',
            field=models.CharField(blank=True, choices=[('serial', 'Seri Port'), ('i2c', 'I2C'), ('virtual', 'Sanal')], max_length=20, verbose_name='Arayüz Tipi'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='parser_type',
            field=models.CharField(blank=True, choices=[('regex', 'Regex'), ('binary', 'Binary Format'), ('simple', 'Basit (Değerin kendisi)')], max_length=20, verbose_name='Veri Ayrıştırıcı Tipi'),
        ),
    ]
