# Generated by Django 5.2.5 on 2025-08-12 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_sensor_interface_alter_sensor_parser_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kamera Adı')),
                ('rtsp_url', models.CharField(max_length=500, verbose_name='RTSP URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('is_recording', models.BooleanField(default=False, verbose_name='Kayıt Yapıyor mu?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='core.device', verbose_name='Bağlı Olduğu İstasyon')),
            ],
            options={
                'verbose_name': 'Kamera',
                'verbose_name_plural': 'Kameralar',
                'unique_together': {('device', 'name')},
            },
        ),
    ]
