# Generated by Django 5.2.5 on 2025-08-12 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='status',
            field=models.CharField(choices=[('active', 'Aktif'), ('maintenance', 'Bakım'), ('offline', 'Offline')], default='active', max_length=15, verbose_name='Durum'),
        ),
        migrations.CreateModel(
            name='CameraCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='camera_captures/%Y/%m/%d/')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captures', to='core.camera')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_type', models.CharField(max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('is_executed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='core.device')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
